// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq1gNLkpU9ENU2sl2D-jgs6gfEUk5GsZs',
    appId: '1:340198289540:ios:2d9769ee36483085b9d2d1',
    messagingSenderId: '340198289540',
    projectId: 'student-manager-nhom4',
    storageBucket: 'student-manager-nhom4.firebasestorage.app',
    iosBundleId: 'com.example.quanLySinhVien',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWSXQXLnTOmU1LactWTcp7BjaK2sv-qbk',
    appId: '1:340198289540:web:7cbc1b08c95460c5b9d2d1',
    messagingSenderId: '340198289540',
    projectId: 'student-manager-nhom4',
    authDomain: 'student-manager-nhom4.firebaseapp.com',
    storageBucket: 'student-manager-nhom4.firebasestorage.app',
    measurementId: 'G-TBDMCFTD72',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq1gNLkpU9ENU2sl2D-jgs6gfEUk5GsZs',
    appId: '1:340198289540:ios:2d9769ee36483085b9d2d1',
    messagingSenderId: '340198289540',
    projectId: 'student-manager-nhom4',
    storageBucket: 'student-manager-nhom4.firebasestorage.app',
    iosBundleId: 'com.example.quanLySinhVien',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW-GkbhtlMxrB7m5QBTBWzv_j4Rvx8znE',
    appId: '1:340198289540:android:0187988a0c1abf69b9d2d1',
    messagingSenderId: '340198289540',
    projectId: 'student-manager-nhom4',
    storageBucket: 'student-manager-nhom4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWSXQXLnTOmU1LactWTcp7BjaK2sv-qbk',
    appId: '1:340198289540:web:dfaf1c490576bacdb9d2d1',
    messagingSenderId: '340198289540',
    projectId: 'student-manager-nhom4',
    authDomain: 'student-manager-nhom4.firebaseapp.com',
    storageBucket: 'student-manager-nhom4.firebasestorage.app',
    measurementId: 'G-ZYY5PDG033',
  );

}